FROM python:3.9-slim

WORKDIR /app

RUN apt-get update && \ 
    apt-get install -y \
    libx11-6 \
    libxext6 \
    libxrender1 \
    libsm6 \
    libxrandr2 \
    libgl1 \
    libglu1-mesa \
    libglib2.0-0 \
    libqt5widgets5 \
    libqt5gui5 \
    libqt5core5a \
    xauth \
    x11-xserver-utils \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir \
    orange3 \
    pyqt5

CMD ["python", "-m", "Orange.canvas"]

