# File: Dockerfile.xeyes
FROM debian:bullseye-slim

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y \
    x11-apps \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

CMD ["xeyes"]
